"""Daily summary report generation in Markdown and HTML."""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path

from aio_monitor.models import DailyRunSummary, RunStatus

logger = logging.getLogger(__name__)

MARKDOWN_TEMPLATE = """# AI Overview Monitor — Daily Report

**Date:** {date}
**Generated:** {generated_at}

---

## Summary

| Metric | Count |
|--------|-------|
| Total keywords checked | {total_keywords} |
| AI Overviews found | {ai_overview_count} |
| Target domains cited | {target_cited_count} |
| Failed checks | {failed_count} |

---

## Top Cited Domains

{top_domains_table}

---

## Detailed Results

{detailed_results_table}

---

## Failed Checks

{failed_checks}

---

*Report generated by AI Overview Monitor*
"""

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Overview Monitor — Daily Report ({date})</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 1000px;
            margin: 0 auto;
            padding: 20px;
            background: #f8f9fa;
            color: #333;
        }}
        h1 {{ color: #1a73e8; border-bottom: 2px solid #1a73e8; padding-bottom: 10px; }}
        h2 {{ color: #333; margin-top: 30px; }}
        .summary-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 15px;
            margin: 20px 0;
        }}
        .summary-card {{
            background: white;
            border-radius: 8px;
            padding: 20px;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
            text-align: center;
        }}
        .summary-card .number {{
            font-size: 2em;
            font-weight: bold;
            color: #1a73e8;
        }}
        .summary-card .label {{
            color: #666;
            margin-top: 5px;
        }}
        .card-success .number {{ color: #34a853; }}
        .card-warning .number {{ color: #fbbc04; }}
        .card-error .number {{ color: #ea4335; }}
        table {{
            width: 100%;
            border-collapse: collapse;
            background: white;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
            margin: 15px 0;
        }}
        th {{
            background: #1a73e8;
            color: white;
            padding: 12px 15px;
            text-align: left;
        }}
        td {{
            padding: 10px 15px;
            border-bottom: 1px solid #eee;
        }}
        tr:hover td {{ background: #f1f3f4; }}
        .status-success {{ color: #34a853; font-weight: bold; }}
        .status-failed {{ color: #ea4335; font-weight: bold; }}
        .status-partial {{ color: #fbbc04; font-weight: bold; }}
        .badge {{
            display: inline-block;
            padding: 2px 8px;
            border-radius: 12px;
            font-size: 0.85em;
            font-weight: bold;
        }}
        .badge-yes {{ background: #e6f4ea; color: #34a853; }}
        .badge-no {{ background: #fce8e6; color: #ea4335; }}
        .badge-na {{ background: #f1f3f4; color: #999; }}
        .screenshot-link {{ color: #1a73e8; text-decoration: none; }}
        .screenshot-link:hover {{ text-decoration: underline; }}
        .meta {{ color: #999; font-size: 0.9em; margin-top: 40px; text-align: center; }}
    </style>
</head>
<body>
    <h1>AI Overview Monitor — Daily Report</h1>
    <p><strong>Date:</strong> {date} &nbsp;|&nbsp; <strong>Generated:</strong> {generated_at}</p>

    <div class="summary-grid">
        <div class="summary-card">
            <div class="number">{total_keywords}</div>
            <div class="label">Keywords Checked</div>
        </div>
        <div class="summary-card card-success">
            <div class="number">{ai_overview_count}</div>
            <div class="label">AI Overviews Found</div>
        </div>
        <div class="summary-card card-warning">
            <div class="number">{target_cited_count}</div>
            <div class="label">Target Domains Cited</div>
        </div>
        <div class="summary-card card-error">
            <div class="number">{failed_count}</div>
            <div class="label">Failed Checks</div>
        </div>
    </div>

    <h2>Top Cited Domains</h2>
    {top_domains_html}

    <h2>Detailed Results</h2>
    {detailed_results_html}

    <h2>Failed Checks</h2>
    {failed_checks_html}

    <p class="meta">Report generated by AI Overview Monitor</p>
</body>
</html>"""


class ReportGenerator:
    """Generates daily summary reports in Markdown and HTML formats."""

    def __init__(self, reports_dir: str | Path) -> None:
        self.reports_dir = Path(reports_dir)
        self.reports_dir.mkdir(parents=True, exist_ok=True)

    def generate_markdown(self, summary: DailyRunSummary) -> str:
        """Generate a Markdown report and save to file. Returns the file path."""
        generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

        # Top cited domains table
        if summary.top_cited_domains:
            top_domains_lines = ["| Domain | Citations |", "|--------|-----------|"]
            for domain, count in list(summary.top_cited_domains.items())[:20]:
                top_domains_lines.append(f"| {domain} | {count} |")
            top_domains_table = "\n".join(top_domains_lines)
        else:
            top_domains_table = "_No cited domains found._"

        # Detailed results table
        detail_lines = [
            "| Keyword | AI Overview | Target Cited | Cited Domains | Screenshot | Status |",
            "|---------|-------------|--------------|---------------|------------|--------|",
        ]
        for r in summary.results:
            ai_badge = "✅" if r.ai_overview_present else "❌"
            target_badge = "✅" if r.target_domain_cited else "—"
            domains_str = ", ".join(r.cited_domains[:5])
            if len(r.cited_domains) > 5:
                domains_str += f" (+{len(r.cited_domains) - 5} more)"
            screenshot_link = f"[📸]({r.screenshot_path})" if r.screenshot_path else "—"
            status = r.run_status
            detail_lines.append(
                f"| {r.keyword} | {ai_badge} | {target_badge} | "
                f"{domains_str or '—'} | {screenshot_link} | {status} |"
            )
        detailed_results_table = "\n".join(detail_lines)

        # Failed checks
        failed = [r for r in summary.results if r.run_status == RunStatus.FAILED.value]
        if failed:
            failed_lines = []
            for r in failed:
                failed_lines.append(f"- **{r.keyword}**: {r.notes}")
            failed_checks = "\n".join(failed_lines)
        else:
            failed_checks = "_No failed checks._"

        content = MARKDOWN_TEMPLATE.format(
            date=summary.run_date,
            generated_at=generated_at,
            total_keywords=summary.total_keywords,
            ai_overview_count=summary.ai_overview_count,
            target_cited_count=summary.target_domain_cited_count,
            failed_count=summary.failed_count,
            top_domains_table=top_domains_table,
            detailed_results_table=detailed_results_table,
            failed_checks=failed_checks,
        )

        output_path = self.reports_dir / f"report_{summary.run_date}.md"
        output_path.write_text(content, encoding="utf-8")
        logger.info("Markdown report saved to %s", output_path)
        return str(output_path)

    def generate_html(self, summary: DailyRunSummary) -> str:
        """Generate an HTML report and save to file. Returns the file path."""
        generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

        # Top cited domains HTML table
        if summary.top_cited_domains:
            rows = []
            for domain, count in list(summary.top_cited_domains.items())[:20]:
                rows.append(f"<tr><td>{domain}</td><td>{count}</td></tr>")
            top_domains_html = (
                "<table><tr><th>Domain</th><th>Citations</th></tr>"
                + "".join(rows)
                + "</table>"
            )
        else:
            top_domains_html = "<p><em>No cited domains found.</em></p>"

        # Detailed results HTML table
        detail_rows = []
        for r in summary.results:
            ai_badge = (
                '<span class="badge badge-yes">Yes</span>'
                if r.ai_overview_present
                else '<span class="badge badge-no">No</span>'
            )
            target_badge = (
                '<span class="badge badge-yes">Yes</span>'
                if r.target_domain_cited
                else '<span class="badge badge-na">—</span>'
            )
            domains_str = ", ".join(r.cited_domains[:5])
            if len(r.cited_domains) > 5:
                domains_str += f" (+{len(r.cited_domains) - 5} more)"

            screenshot_cell = (
                f'<a class="screenshot-link" href="{r.screenshot_path}">View</a>'
                if r.screenshot_path
                else "—"
            )
            status_class = f"status-{r.run_status}"
            detail_rows.append(
                f"<tr>"
                f"<td>{r.keyword}</td>"
                f"<td>{ai_badge}</td>"
                f"<td>{target_badge}</td>"
                f"<td>{domains_str or '—'}</td>"
                f"<td>{screenshot_cell}</td>"
                f'<td class="{status_class}">{r.run_status}</td>'
                f"</tr>"
            )
        detailed_results_html = (
            "<table><tr>"
            "<th>Keyword</th><th>AI Overview</th><th>Target Cited</th>"
            "<th>Cited Domains</th><th>Screenshot</th><th>Status</th>"
            "</tr>"
            + "".join(detail_rows)
            + "</table>"
        )

        # Failed checks HTML
        failed = [r for r in summary.results if r.run_status == RunStatus.FAILED.value]
        if failed:
            failed_items = "".join(
                f"<li><strong>{r.keyword}</strong>: {r.notes}</li>" for r in failed
            )
            failed_checks_html = f"<ul>{failed_items}</ul>"
        else:
            failed_checks_html = "<p><em>No failed checks.</em></p>"

        content = HTML_TEMPLATE.format(
            date=summary.run_date,
            generated_at=generated_at,
            total_keywords=summary.total_keywords,
            ai_overview_count=summary.ai_overview_count,
            target_cited_count=summary.target_domain_cited_count,
            failed_count=summary.failed_count,
            top_domains_html=top_domains_html,
            detailed_results_html=detailed_results_html,
            failed_checks_html=failed_checks_html,
        )

        output_path = self.reports_dir / f"report_{summary.run_date}.html"
        output_path.write_text(content, encoding="utf-8")
        logger.info("HTML report saved to %s", output_path)
        return str(output_path)

    def generate(self, summary: DailyRunSummary) -> tuple[str, str]:
        """Generate both Markdown and HTML reports. Returns (md_path, html_path)."""
        md_path = self.generate_markdown(summary)
        html_path = self.generate_html(summary)
        return md_path, html_path
